/*
 * This file was generated - do not edit it directly !!
 * Generated by AuDAO tool, a product of Spolecne s.r.o.
 * For more information please visit http://www.spoledge.com
 */
package com.mobile.dao;

import java.sql.Date;
import java.sql.Timestamp;

import com.spoledge.audao.db.dao.AbstractDao;
import com.spoledge.audao.db.dao.DaoException;

import com.mobile.dto.Log;


/**
 * This is the DAO.
 *
 * @author generated
 */
public interface LogDao extends AbstractDao {

    /**
     * Finds a record identified by its primary key.
     * @return the record found or null
     */
    public Log findByPrimaryKey( int logId );

    /**
     * Finds records ordered by timeEntered.
     */
    public Log[] findAll( );

    /**
     * Deletes records.
     * @return the number of records deleted
     */
    public int deleteAll( ) throws DaoException;

    /**
     * Inserts a new record.
     * @return the generated primary key - logId
     */
    public int insert( Log dto ) throws DaoException;

    /**
     * Updates one record found by primary key.
     * @return true iff the record was really updated (=found and any change was really saved)
     */
    public boolean update( int logId, Log dto ) throws DaoException;

}
