/*
 * This file was generated - do not edit it directly !!
 * Generated by AuDAO tool, a product of Spolecne s.r.o.
 * For more information please visit http://www.spoledge.com
 */
package com.mobile.dao;

import java.sql.Date;
import java.sql.Timestamp;

import com.spoledge.audao.db.dao.AbstractDao;
import com.spoledge.audao.db.dao.DaoException;

import com.mobile.dto.Contact;


/**
 * This is the DAO.
 *
 * @author generated
 */
public interface ContactDao extends AbstractDao {

    /**
     * Finds a record identified by its primary key.
     * @return the record found or null
     */
    public Contact findByPrimaryKey( int contactId );

    /**
     * Finds records ordered by name.
     */
    public Contact[] findAll( );

    /**
     * Deletes a record identified by its primary key.
     * @return true iff the record was really deleted (existed)
     */
    public boolean deleteByPrimaryKey( int contactId ) throws DaoException;

    /**
     * Inserts a new record.
     * @return the generated primary key - contactId
     */
    public int insert( Contact dto ) throws DaoException;

    /**
     * Updates one record found by primary key.
     * @return true iff the record was really updated (=found and any change was really saved)
     */
    public boolean update( int contactId, Contact dto ) throws DaoException;

}
