/*
 * This file was generated - do not edit it directly !!
 * Generated by AuDAO tool, a product of Spolecne s.r.o.
 * For more information please visit http://www.spoledge.com
 */
package com.mobile.dao.mysql;

import java.sql.Connection;

import com.mobile.dao.*;


/**
 * This is the main implementation class for obtaining DAO objects.
 * @author generated
 */
public class DaoFactoryImpl extends DaoFactory.Factory {
    public ContactDao createContactDao( Connection conn ) {
        return new ContactDaoImpl( conn );
    }

    public LogDao createLogDao( Connection conn ) {
        return new LogDaoImpl( conn );
    }

}
