spring.application.name=productlcense
server.port=8081

spring.datasource.url=jdbc:hsqldb:file:/opt/wizard/database/db/license;ifexists=true;hsqldb.lock_file=false
spring.datasource.password=
spring.datasource.username=SA

## common settings
                                                                               

spring.jpa.hibernate.ddl-auto=none
spring.datasource.initialization-mode=always
spring.jpa.properties.hibernate.type=trace

spring.datasource.driver-class-name=org.hsqldb.jdbc.JDBCDriver

spring.jmx.default-domain: test

endpoints.shutdown.sensitive=false
endpoints.shutdown.enabled=true
